export const Dropdown: string;
export const title: string;
export const optionsContainer: string;
export const selectorPointyTop: string;
export const selectableOptionName: string;
export const nested1LevelOptionName: string;
export const nested2LevelsOptionName: string;
export const backdropToCatchClicksAwayFromSelector: string;
export const optionsContainerVisible: string;
